language: python
python:
  #- "3.4"
  #- "3.3"
  #- "3.2"
  - "2.7"
  - "pypy"
script: nosetests
install:
  - "pip install -r development.txt"
  - "if [ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]; then pip install gevent; fi"
  - "pip install nose"
services:
  - rabbitmq
